/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docSidebar: [
    {type: 'autogenerated', dirName: '.'},
    {
      'Resources': [
        {
          'Client Library References': [
            {
              type: 'link',
              label: 'divviup-ts (TypeScript)',
              href: 'https://docs.divviup.org/divviup-ts',
            },
            {
              type: 'link',
              label: 'janus_client (Rust)',
              href: 'https://docs.rs/janus_client/latest/janus_client/',
            },
          ]
        },
        {
          type: 'link',
          label: 'Divvi Up API Reference',
          href: 'https://app.divviup.org/swagger-ui',
        },
        {
          'IETF Specifications': [
            {
              type: 'link',
              label: 'Distributed Aggregation Protocol (DAP)',
              href: 'https://datatracker.ietf.org/doc/draft-ietf-ppm-dap/',
            },
            {
              type: 'link',
              label: 'Verifiable Distributed Aggregation Functions (VDAF)',
              href: 'https://datatracker.ietf.org/doc/draft-irtf-cfrg-vdaf/',
            },
          ]
        },
      ]
    }
  ],
};

module.exports = sidebars;
